### ISSUE TITLE
Typo in the README.md file

### ISSUE THREAD

**Issue by pmsoltani** [tiangolo/docker-with-compose#12]
Inside the [Description](https://github.com/tiangolo/docker-with-compose#description) section of the `README.md` file, there is a typo:

The main purpose of this image is to help in Continuous Integration environments that need the docker binary, the docker-compose binary and **posibly (possibly)** require doing other things, like running Bash scripts.

**Comment by tiangolo** [comment]
Thanks! Good catch. :pencil2: :heavy_check_mark: 

I just fixed it.
