### ISSUE TITLE
[FEATURE] Document how to mount the Docker sock

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/docker-with-compose#13]
Document how to mount the Docker sock as a volume so that Docker Compose inside the container can have access to the local Docker service/daemon.

This has to be done instead of Docker-in-Docker: http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

Probably with the ideas here: https://medium.com/better-programming/about-var-run-docker-sock-3bfd276e12fd

**Comment by ac3d912** [comment]
Here's what I got working for the docker-runner config.toml.

```
[[runners]]
...
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock","/cache"]
    shm_size = 0
```

For the runner, just make sure to run it with `-v /var/run/docker.sock:/var/run/docker.sock`

Didn't need to make any changes to the .gitlab-ci.yml.

**Comment by tiangolo** [comment]
Thanks @ac3d912 ! Yep. I wanted to add more general instructions apart from GitLab Runners.

But I just did! :rocket: :heavy_check_mark:
