### ISSUE TITLE
Can't access compose container port on localhost in Gitlab CI

### ISSUE THREAD

**Issue by blevine** [tiangolo/docker-with-compose#16]
Hi,

I have a docker-compose.yaml that runs the Keycloak SSO server and Postgresql.  The Keycloak HTTP server listens on port 8080 and so I have
```
-ports
  8080:8080
```
in the docker-compose.yaml.

In my .gitlab-ci.yml I do: `docker-compose -f path/to/docker.compose.yaml up -d`. I then start a watchdog so that I know when Keycloak is available by doing a `curl -I http://localhost:8080` in a loop-with-sleep checking curl's exit status.

However, I get connection refused even when I know the Keycloak is up and running. I'm sure there's something I don't understand here.  What is it?

**Comment by tiangolo** [comment]
The `localhost` inside of the Docker Compose container is going to refer to the same container, you won't be able to connect to something else running on the host machine.

If you can, for example, put that on a domain, then you can curl that domain.

**Comment by blevine** [comment]
Thanks. I actually figured out a solution using Docker-in-Docker (dind) running as a gitlab-ci "service". The Keycloak server is then addressable using the dind container's hostname which I've aliased to "dind".  So http://dind:8080 instead of http://localhost:8080
