### ISSUE TITLE
proposal: include `docker-auto-labels`

### ISSUE THREAD

**Issue by iAnanich** [tiangolo/docker-with-compose#17]
In [full-stack-fastapi-postgresql](https://github.com/tiangolo/full-stack-fastapi-postgresql) cookiecutter repo `docker-auto-labels` were used, and I think that including this package could speedup each CI pipeline a bit.

**Comment by tiangolo** [comment]
Thanks! I'm currently not sure Docker Swarm mode would be the way to go in the future 😔 

So I would prefer not to add that here to this package. I also have to give that project generator a big update.

Given that I'll pass on this one. But thanks for the interest! ☕
