### ISSUE TITLE
proposal: include `gettext`

### ISSUE THREAD

**Issue by iAnanich** [tiangolo/docker-with-compose#18]
`gettext` allows me to use `envsubst` which is nice for configuring rendering `docker-compose.yml` with external secrets, networks etc as their names better to be stored as CI variables rather as hardcoded value in `docker-compose.yml`.

**Comment by tiangolo** [comment]
You can use environment variables in docker-compose files: https://docs.docker.com/compose/compose-file/#service-configuration-reference

In any case, there are many different tools that would work for each individual use case, so I would prefer to keep this as simple as possible. If you find yourself needing some other tools frequently, I think it would be better to create a new re-usable image that works best for you.

**Comment by iAnanich** [comment]
Fair enough )
Actually, I'm using env vars lately. The reason behind gettext was to make some attributes changeable (like network name, volume name, secret name). But further digging into Docker Compose documentation and newer versions revealed that all of them can have external name specified with env var while keeping internal (in context of single docker compose) name constant.
