### ISSUE TITLE
CURL

### ISSUE THREAD

**Issue by KrolikROJER** [tiangolo/docker-with-compose#2]
can you add curl installation? may with same tag on docker image

```
FROM docker:latest

RUN apk add --no-cache curl
RUN apk add --no-cache py-pip
RUN pip install docker-compose
```

**Comment by tiangolo** [comment]
I'm curious, what would be the use case for this?

**Comment by stratosgear** [comment]
May I provide a reasonable usecase?

I would like to send a chat notification when some build process finishes, with an incoming hook on the chat app!

Would you reconsider adding such a basic command line utility tool?  It **is** being used inside a gitlab ci pipeline anyways, where automations like these are frequently performed.

**Comment by tiangolo** [comment]
Yep. That makes sense. Thanks for the PR! :tada:
