### ISSUE TITLE
GitLab CI/CD - Couldn't connect to docker daemon

### ISSUE THREAD

**Issue by nicolabeghin** [tiangolo/docker-with-compose#20]
Hi everyone
I just tried to use this useful image but getting error trying a simple `docker-compose build` ?

`.gitlab-ci.yml`seems to me like copy-pasted from official docs, not sure I'm missing something? pretty new to GitLab builds, so I could miss something obvious.
![image](https://user-images.githubusercontent.com/2743637/108632634-3fc58300-7470-11eb-87b7-27dcc8c2408c.png)

Output from CI:
![image](https://user-images.githubusercontent.com/2743637/108632733-c11d1580-7470-11eb-9c25-969adb31e3c9.png)

thanks
nicola

**Comment by xtccc** [comment]
### your dockr containter coun't find the docker socket , 
### Did your /etc/gitlab-runner/config.toml has the  ```volumes = ["/var/run/docker.sock:/var/run/docker.sock"```, ? 
### I think the reason is that , you add the volumes adbout docker.sock to the gitlab-runner 's config can  solve the problem.

**Comment by nicolabeghin** [comment]
Thanks, in the end I found out in other issues documentation and moved to standard compose image

![image](https://user-images.githubusercontent.com/2743637/109797454-cc630480-7c19-11eb-9dac-134221769c42.png)

**Comment by tiangolo** [comment]
Thanks for the help here @xtccc !

Thanks for reporting back and closing the issue @nicolabeghin  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
