### ISSUE TITLE
Docker-compose now requires Alpine cargo package

### ISSUE THREAD

**Issue by chuckhoupt** [tiangolo/docker-with-compose#21]
The Dockerfile fails to build now because `apt-get install cargo` is required for docker-compose. See:

https://docs.docker.com/compose/install/#alternative-install-options

**Comment by tiangolo** [comment]
Thanks! This was solved in some PR some time ago, so this should be solved now. :nerd_face: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
