### ISSUE TITLE
Bash

### ISSUE THREAD

**Issue by rudolfbyker** [tiangolo/docker-with-compose#22]
The README says:

> This image allows running arbitrary commands like Bash scripts,

But the image does not contain bash. I propose we `apk add bash`.

**Comment by tiangolo** [comment]
Good catch! I just updated the README to instead say "shell", as I would rather not add another dependency.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
