### ISSUE TITLE
Time ot sunset this repo?

### ISSUE THREAD

**Issue by n1ngu** [tiangolo/docker-with-compose#45]
Now that compose has been added into the official docker image (https://github.com/docker-library/docker/pull/361) what is the purpose of this repository anymore?

Is it time to tell folks to stop using it? Should it become a plain mirror for `docker:latest`?

**Comment by tiangolo** [comment]
Indeed! I'm deprecating and archiving it. https://github.com/tiangolo/docker-with-compose/pull/47

Thanks!
