### ISSUE TITLE
somehow not working anymore with gitlab

### ISSUE THREAD

**Issue by step21** [tiangolo/docker-with-compose#5]
I had your image (thanks very much) set up with a private gitlab instance, but it just stopped working. Though there are no obvious changes on the server where it is executed nor in your repo. But maybe you have some idea?
config.toml and erros message below.

    Running with gitlab-runner 11.11.2 (ac2a293c)
      on homeserver something
    Using Docker executor with image tiangolo/docker-with-compose ...
    Starting service docker:dind ...
    Pulling docker image docker:dind ...
    Using docker image sha256:6ce0d31cf4d670f84b0f74b1b15910f9e3fde4105232e14b0d360a6a49c05362 for docker:dind ...
    Waiting for services to be up and running...
    Pulling docker image tiangolo/docker-with-compose ...
    Using docker image sha256:cf0fa05056110e8c9866200f6879b615ea55be3e54f558826aab5b0882537f70 for tiangolo/docker-with-compose ...
    Running on runner-something-0 via ubuntu...
    DEPRECATION: this GitLab server doesn't support refspecs, gitlab-runner 12.0 will no longer work with this version of GitLab
    Fetching changes...
    Checking out 13232142 as somebranch...
    
    Skipping Git submodules setup
    $ docker-compose up -d
    Couldn't connect to Docker daemon at http://docker:2375 - is it running?
    
    If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
    ERROR: Job failed: exit code 1

config.toml

    concurrent = 1
    check_interval = 0
    
    [session_server]
    session_timeout = 1800
    
    [[runners]]
    name = "homeserver"
    url = "https://gitlab.something.eu/"
    token = "<sometoken>"
    executor = "docker"
    [runners.custom_build_dir]
    [runners.docker]
    tls_verify = false
    image = "tiangolo/docker-with-compose"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    [runners.cache]
      [runners.cache.s3]
      [runners.cache.gcs]

**Comment by step21** [comment]
I tried, fixing all images to version 18, as in gitlab forums there are some reports that due to some docker update but no gitlab update, things stopped working. However so far that did not help.
Any ideas, or anybody else seeing this?

**Comment by step21** [comment]
This was due to https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/7309 and a docker upgrade breaking stuff. Even stable was affected. It could be avoided by pinning to a specific image instead of latest.
For now the fix is to disable certs with `DOCKER_TLS_CERTDIR: ""` in the .gitlab-ci.yml and in the runner config.toml. Additionally for me an issue with local testing was that gitlab-runner (when run manually) does not respect `/etc/gitlab-runner/config.toml` so it was not running in privileged mode, which I didn't notice, but which is necessary for docker in docker.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
