### ISSUE TITLE
Running docker-compose on python3 would work better

### ISSUE THREAD

**Issue by ollisal** [tiangolo/docker-with-compose#7]
docker-compose has some annoying bugs running on python2, e.g. [not seeing log output of services that have been idle for some time](https://github.com/docker/docker-py/issues/2425)

Furthermore, docker-compose is considering deprecating [using it on Python 2 altogether](https://github.com/docker/compose/issues/6890).

We should use a base image with Python 3 and run docker-compose on that instead of Python 2.

**Comment by ollisal** [comment]
My fork at https://github.com/JaksoSoftware/docker-with-compose uses Python 3.8.

Published as [ollisal/docker-with-compose](https://hub.docker.com/repository/docker/ollisal/docker-with-compose)

**Comment by tiangolo** [comment]
Good idea! Thanks. :rocket: 

I just updated it in https://github.com/tiangolo/docker-with-compose/pull/15

**Comment by ollisal** [comment]
Nice!
